# Generated by Django 4.1.5 on 2023-01-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
